import React from "react";
import "@/styles/policy.scss";
import Link from "next/link";

const PolicyPage = () => {
  return (
    <section className="policy">
      <div className="_container">
        <h1>Terms and conditions</h1>
        <span className="date">Last Updated: 30 July, 2024</span>
        <div className="content">
          <h2>General Terms</h2>
          <p>
            By accessing and placing an order with Spectrum Consults, you
            confirm that you agree to and are bound by the terms of service in
            the Terms and Conditions outlined below. These terms apply to the
            entire website and any email or other communication between you and
            SPECTRUM GROWTH LIMITED with its registered address at 128 City
            Road, London, United Kingdom, EC1V 2NX, registration number
            15810537, email{" "}
            <a href="mailto:info@spectrumconsults.io">
              info@spectrumconsults.io
            </a>
            , and phone number +442070434509.
          </p>
          <h2>Licence Agreement</h2>
          <p>
            These Terms and Conditions are a contract between you and SPECTRUM
            GROWTH LIMITED (referred to in these Terms and Conditions as
            &ldquo;Spectrum Consults,&rdquo; &ldquo;us,&rdquo; &ldquo;we,&rdquo;
            or &ldquo;our&rdquo;), the provider of the Spectrum Consults website
            (
            <a href="https://spectrumconsults.io/">
              https://spectrumconsults.io/
            </a>
            ) and the services accessible from the Spectrum Consults website
            (which are collectively referred to in these Terms and Conditions as
            the &ldquo;Spectrum Consults Service&rdquo;).
          </p>
          <p>
            You agree to be bound by these Terms and Conditions. If you disagree
            with them, please do not use the Spectrum Consults Service. In these
            Terms and Conditions, &ldquo;you&rdquo; refers to you as an
            individual and the entity you represent. If you violate any of these
            Terms and Conditions, we reserve the right to cancel your account or
            block access to your account without notice.
          </p>
          <h2>Definitions</h2>
          <p>For these Terms and Conditions:</p>
          <ul>
            <li>
              <strong>Cookie:</strong> Small data generated by a website and
              saved by your web browser. It is used to identify your browser,
              provide analytics, and remember information about you, such as
              your language preference or login information.
            </li>
            <li>
              <strong>Company:</strong> When this policy mentions
              &ldquo;Company,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
              &ldquo;our,&rdquo; it refers to SPECTRUM GROWTH LIMITED (128 City
              Road, London, United Kingdom, EC1V 2NX), which is responsible for
              your information under these Terms and Conditions.
            </li>
            <li>
              <strong>Country:</strong> Where Spectrum Consults or the
              owners/founders of Spectrum Consults are based, in this case, is
              the United Kingdom.
            </li>
            <li>
              <strong>Device:</strong> Any internet-connected device, such as a
              phone, tablet, computer, or other device, can be used to visit
              Spectrum Consults and use the services.
            </li>
            <li>
              <strong>Service:</strong> Refers to the service provided by
              Spectrum Consults as described in the relative terms (if
              available) and on this platform.
            </li>
            <li>
              <strong>Third-Party Service:</strong> Relates to advertisers,
              contest sponsors, promotional and marketing partners, and others
              who provide our content or whose products or services we think may
              interest you.
            </li>
            <li>
              <strong>Website:</strong> SPECTRUM GROWTH LIMITED&rsquo;s site can
              be accessed via this URL:{" "}
              <a href="https://spectrumconsults.io/">
                https://spectrumconsults.io/
              </a>
              .
            </li>
            <li>
              <strong>You:</strong> A person or entity registered with Spectrum
              Consults to use the Services.
            </li>
          </ul>
          <h2>Feedback and Suggestions</h2>
          <p>
            Any feedback, comments, ideas, improvements, or suggestions
            (collectively, &ldquo;Suggestions&rdquo;) you provide to Spectrum
            Consults regarding the website shall remain the sole and exclusive
            property of Spectrum Consults. Spectrum Consults shall be free to
            use, copy, modify, publish, or redistribute the Suggestions for any
            purpose without any credit or compensation to you.
          </p>
          <h2>Consent</h2>
          <p>
            We&rsquo;ve updated our Terms and Conditions to provide complete
            transparency into what is being set when you visit our site and how
            it&rsquo;s used. By using our website, registering an account, or
            purchasing, you now consent to our Terms and Conditions.
          </p>
          <h2>External Services</h2>
          <p>
            We may display, include, or make available third-party content
            (including data, information, applications, and other product
            services) or provide links to third-party websites or services
            (&ldquo;External Services&rdquo;). You acknowledge and agree that
            Spectrum Consults shall not be responsible for any external
            services, including their accuracy, completeness, timeliness,
            validity, copyright compliance, legality, decency, quality, or any
            other aspect thereof. Spectrum Consults does not assume and shall
            not have any liability or responsibility to you or any other person
            or entity for any third-party services.&nbsp;
          </p>
          <h2>Duration and Termination</h2>
          <p>
            This Agreement shall remain in effect until you or Spectrum Consults
            terminates it. In its sole discretion, Spectrum Consults may suspend
            or terminate this Agreement with or without prior notice at any time
            and for any or no reason. This Agreement will terminate immediately,
            without prior notice from Spectrum Consults, in the event that you
            fail to comply with any provision of this Agreement. You may also
            terminate this Agreement by deleting the website and all copies
            thereof from your computer.
          </p>
          <h2>Other Websites Links</h2>
          <p>
            These Terms and Conditions apply only to the Services. The Services
            may contain links to websites not operated or controlled by Spectrum
            Consults. We are not responsible for the content, accuracy, or
            opinions expressed on such websites, and such websites are not
            investigated, monitored, or checked for accuracy or completeness by
            us. Please remember that when you use a link from the Services to
            another website, our Terms and Conditions are no longer in effect.
            Your browsing and interaction on any other website, including those
            with a link on our platform, is subject to that website&rsquo;s
            rules and policies. Third parties may use their own cookies or other
            methods to collect information about you.
          </p>
          <h2>Cookie Policy</h2>
          <p>
            Spectrum Consults uses &ldquo;Cookies&rdquo; to identify the areas
            of our website that you have visited. A cookie is a small piece of
            data stored on your computer or mobile device by your web browser.
            We use cookies to enhance the performance and functionality of our
            website, but they are non-essential to their use.
          </p>
          <p>
            However, without these cookies, certain functionality, like videos,
            may become unavailable, or you would be required to enter your login
            details every time you visit the website, as we could not remember
            that you had logged in previously. Most web browsers can be set to
            disable the use of Cookies. However, if you disable Cookies, you may
            not be able to access functionality on our website correctly or at
            all. We never place Personally Identifiable Information in Cookies.
          </p>
          <h2>Copyright Notice</h2>
          <p>
            If you are a copyright owner or such owner&rsquo;s agent and believe
            any material on our website constitutes an infringement on your
            copyright, please get in touch with us setting forth the following
            information:
          </p>
          <ol>
            <li>
              A physical or electronic signature of the copyright owner or
              someone authorised to act on his behalf.
            </li>
            <li>
              Identification of the material that is claimed to be infringing.
            </li>
            <li>
              Your contact information, including your address, telephone
              number, and email.
            </li>
            <li>
              A statement by you that you have a good faith belief that the
              copyright owners do not authorise the use of the material.
            </li>
            <li>
              A statement that the information in the notification is accurate
              and that you are authorised to act on behalf of the owner under
              penalty of perjury.
            </li>
          </ol>
          <h2>Warranty Disclaimer</h2>
          <p>
            The website is provided to you &ldquo;AS IS&rdquo; and &ldquo;AS
            AVAILABLE&rdquo; with all faults and defects without warranty of any
            kind. To the maximum extent permitted under applicable law, Spectrum
            Consults, on its behalf and behalf of its affiliates and their
            respective licensors and service providers, expressly disclaims all
            warranties, whether express, implied, statutory, or otherwise,
            concerning the website, including all implied warranties of
            merchantability, fitness for a particular purpose, title and
            non-infringement, and warranties that may arise out of a course of
            dealing, course of performance, usage or trade practice.
          </p>
          <p>
            Without limitation to the preceding, Spectrum Consults provides no
            warranty or undertaking. It makes no representation of any kind that
            the website will meet your requirements, achieve any intended
            results, be compatible or work with any other software, systems, or
            services, operate without interruption, meet any performance or
            reliability standards, or be error-free or that any errors or
            defects can or will be corrected. Without limiting the preceding,
            neither Spectrum Consults nor any Spectrum Consults provider makes
            any representation or warranty of any kind, express or implied:
          </p>
          <ol>
            <li>
              Regarding the operation or availability of the website or the
              information, content, materials, or products we included thereon.
            </li>
            <li>That the website will be uninterrupted or error-free.</li>
            <li>
              As to the accuracy, reliability, or currency of any information or
              content provided through the website.
            </li>
            <li>
              The website, its servers, the content, or emails sent from or on
              behalf of Spectrum Consults are free of viruses, scripts, trojan
              horses, worms, malware, time bombs, or other harmful components.
            </li>
          </ol>
          <p>
            Some jurisdictions do not allow the exclusion of or limitations on
            implied warranties or the applicable statutory rights of a consumer,
            so some or all of the above exclusions and limitations may not apply
            to you.
          </p>
          <h2>Liability Limitation</h2>
          <p>
            Notwithstanding any damages you might incur, Spectrum Consults and
            any of its suppliers&rsquo; entire liability under any provision of
            this Agreement and your exclusive remedy for all of the foregoing
            shall be limited to the amount paid by you for the website.
          </p>
          <p>
            To the maximum extent permitted by applicable law, in no event shall
            Spectrum Consults or its suppliers be liable for any special,
            incidental, indirect, or consequential damages whatsoever
            (including, but not limited to, damages for loss of profits, for
            loss of data or other information, for business interruption, for
            personal injury, for loss of privacy arising out of or in any way
            related to the use of or inability to use the website, third-party
            software and/or third-party hardware used with the website, or
            otherwise in connection with any provision of this Agreement), even
            if Spectrum Consults or any supplier has been advised of the
            possibility of such damages and even if the remedy fails of its
            essential purpose.
          </p>
          <p>
            Some jurisdictions do not allow the exclusion or limitation of
            incidental or consequential damages, so the above limitation or
            exclusion may not apply to you.
          </p>
          <h2>Compensation</h2>
          <p>
            You agree to indemnify and hold Spectrum Consults and its parents,
            subsidiaries, affiliates, officers, employees, agents, partners, and
            licensors (if any) harmless from any claim or demand, including
            reasonable attorneys&rsquo; fees, due to or arising out of your:
          </p>
          <ol>
            <li>Use of the website.</li>
            <li>Violation of this Agreement or any law or regulation.</li>
            <li>Violation of any right of a third party.</li>
          </ol>
          <h2>Severability</h2>
          <p>
            This Agreement, together with the Privacy Policy and any other legal
            notices published by Spectrum Consults on the Services, shall
            constitute the entire Agreement between you and Spectrum Consults
            concerning the Services. Suppose any provision of this Agreement is
            deemed invalid by a court of competent jurisdiction. In that case,
            the invalidity of such provision shall not affect the validity of
            the remaining provisions of this Agreement, which shall remain in
            full force and effect.
          </p>
          <p>
            No waiver of any term of this Agreement shall be deemed a further or
            continuing waiver of such or any other term. Spectrum
            Consults&rsquo;s failure to assert any right or provision under this
            Agreement shall not constitute a waiver of such right or provision.
            You and Spectrum Consults agree that any cause of action arising
            from or related to the services must commence within one (1) Year
            after the cause of action accrues. Otherwise, such cause of action
            is permanently barred.
          </p>
          <h2>Rights Waiver</h2>
          <p>
            Except as provided herein, a party&rsquo;s failure to exercise a
            right or to require the performance of an obligation under this
            Agreement shall not affect its ability to exercise such right or
            require such performance at any time after that, nor shall the
            waiver of a breach constitute waiver of any subsequent breach.
          </p>
          <h2>Complete Agreement</h2>
          <p>
            The Agreement constitutes the entire Agreement between you and
            Spectrum Consults regarding your website use. It supersedes all
            prior and contemporaneous written or oral agreements.
          </p>
          <p>
            You may be subject to additional terms and conditions when you use
            or purchase other Spectrum Consults services, which Spectrum
            Consults will provide at the time of such use or purchase.
          </p>
          <h2>Modifications to This Agreement</h2>
          <p>
            Spectrum Consults reserves the right to modify or replace this
            Agreement at any time. If a revision is material, we will provide at
            least 30 days&rsquo; notice before any new terms take effect. What
            constitutes a material change will be determined at our sole
            discretion.&nbsp;
          </p>
          <p>
            By continuing to access or use our website after any revisions
            become effective, you agree to be bound by the revised terms. If you
            disagree with the new terms, you can no longer use Spectrum
            Consults.
          </p>
          <h2>Intellectual Property Rights</h2>
          <p>
            The website and its entire contents, features, and functionality
            (including but not limited to all information, software, text,
            displays, images, video and audio, and the design, selection, and
            arrangement thereof) are owned by Spectrum Consults. The United
            Kingdom and international copyright, trademark, patent, trade
            secret, and other intellectual property or proprietary rights laws
            protect its licensors or other providers of such material.
          </p>
          <p>
            The material may not be copied, modified, reproduced, downloaded, or
            distributed in any way, in whole or in part, without the express
            prior written permission of Spectrum Consults, unless and except as
            is expressly provided in these Terms and Conditions. Any
            unauthorised use of the material is prohibited.&nbsp;
          </p>
          <p>
            By continuing to access or use our website after any revisions
            become effective, you agree to be bound by the revised terms. If you
            disagree with the new terms, you can no longer use Spectrum
            Consults.
          </p>
          <h2>Arbitration Agreement</h2>
          <p>
            This section applies to any dispute, except it doesn&rsquo;t include
            a dispute relating to claims for injunctive or equitable relief
            regarding the enforcement or validity of your or Spectrum
            Consults&rsquo;s intellectual property rights. The term
            &ldquo;dispute&rdquo; means any dispute, action, or other
            controversies between you and Spectrum Consults concerning the
            Services or this Agreement, whether in contract, warranty, tort,
            statute, regulation, ordinance, or any other legal or equitable
            basis. &ldquo;Dispute&rdquo; will be given the broadest possible
            meaning allowable under law.
          </p>
          <h2>Mandatory Arbitration</h2>
          <p>
            Suppose you and Spectrum Consults do not resolve any dispute by
            informal negotiation. In that case, any other effort to resolve the
            dispute will be conducted exclusively by binding arbitration, as
            described in this section. You are giving up the right to litigate
            (or participate as a party or class member) all disputes in court
            before a judge or jury. The dispute shall be settled by binding
            arbitration by the commercial arbitration rules of the London Court
            of International Arbitration.
          </p>
          <p>
            Either party may seek any interim or preliminary injunctive relief
            from any court of competent jurisdiction as necessary to protect the
            party&rsquo;s rights or property pending the completion of
            arbitration. The non-prevailing party shall bear all legal,
            accounting, and other costs, fees, and expenses incurred by the
            prevailing party.
          </p>
          <h2>Dispute Notification</h2>
          <p>
            In the event of a dispute, you or Spectrum Consults must give the
            other a Notice of Dispute, a written statement that sets forth the
            name, address, and contact information of the party giving it, the
            facts giving rise to the dispute, and the relief requested. You must
            send any Notice of Dispute via email to{" "}
            <a href="mailto:info@spectrumconsults.io">
              info@spectrumconsults.io
            </a>
            . Spectrum Consults will send any Notice of Dispute to you by mail
            to your address if we have it or otherwise to your email address.
            You and Spectrum Consults will attempt to resolve any dispute
            through informal negotiation within sixty (60) days from the date
            the Notice of Dispute is sent. After sixty (60) days, you or
            Spectrum Consults may commence arbitration.
          </p>
          <h2>Privacy and Submissions</h2>
          <p>
            Suppose you submit or post any ideas, creative suggestions, designs,
            photographs, information, advertisements, data, or proposals,
            including ideas for new or improved products, services, features,
            technologies, or promotions. In that case, you agree that such
            submissions will automatically be treated as non-confidential and
            non-proprietary and will become the sole property of Spectrum
            Consults without any compensation or credit to you whatsoever.
          </p>
          <p>
            Spectrum Consults and its affiliates shall have no obligations
            concerning such submissions or posts. They may use the ideas
            contained in such submissions or posts for any purposes in any
            medium in perpetuity, including, but not limited to, developing
            manufacturing and marketing products and services using such ideas.
          </p>
          <h2>Errors and Corrections</h2>
          <p>
            If a product and/or service is listed at an incorrect price or with
            incorrect information due to a typographical error, we shall have
            the right to refuse or cancel any orders placed for the product
            and/or service listed at the incorrect price. We shall have the
            right to refuse or cancel any such order whether or not the order
            has been confirmed and your credit card charged. If your credit card
            has already been charged for the purchase and your order is
            cancelled, we shall immediately issue a credit to your credit card
            account or other payment accounts in the amount of the charge.
          </p>
          <h2>General Disclaimer</h2>
          <p>
            Spectrum Consults is not responsible for content, code, or other
            imprecision. Spectrum Consults does not provide warranties or
            guarantees. In no event shall Spectrum Consults be liable for any
            special, direct, indirect, consequential, or incidental damages or
            any damages whatsoever, whether in an action of contract,
            negligence, or other torts, arising out of or in connection with the
            use of the Service or the contents of the Service. Spectrum Consults
            reserves the right to make additions, deletions, or modifications to
            the contents of the Service at any time without prior notice.
          </p>
          <p>
            The Spectrum Consults Service and its contents are provided
            &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without any
            warranty or representations, express or implied. Spectrum Consults
            is a distributor and not a publisher of the content supplied by
            third parties; as such, Spectrum Consults exercises no editorial
            control over such content and makes no warranty or representation as
            to the accuracy, reliability, or currency of any information,
            content, service or merchandise provided through or accessible via
            the Spectrum Consults Service.
          </p>
          <h2>Contact Information</h2>
          <p>
            If you have any questions about these Terms, please get in touch
            with Spectrum Consults:
          </p>
          <ul>
            <li>
              Via email at{" "}
              <a href="mailto:info@spectrumconsults.io">
                info@spectrumconsults.io
              </a>
              ;
            </li>
            <li>By phone at +442070434509;</li>
            <li>
              Or through the contact form provided on the website:{" "}
              <a href="https://spectrumconsults.io/get-in-touch">
                https://spectrumconsults.io/get-in-touch
              </a>
              .
            </li>
          </ul>
        </div>
      </div>
    </section>
  );
};

export default PolicyPage;
