import React from "react";
import "@/styles/policy.scss";
import Link from "next/link";

const PolicyPage = () => {
  return (
    <section className="policy">
      <div className="_container">
        <h1>Privacy Policy</h1>
        <div className="content">
          <p>
            SPECTRUM GROWTH LIMITED(&ldquo;Spectrum Consults,&rdquo;
            &ldquo;we,&rdquo; &ldquo;our,&rdquo; or &ldquo;us&rdquo;) with its
            registered address at 128 City Road, London, United Kingdom, EC1V
            2NX, registration number 15810537, email{" "}
            <a href="mailto:info@spectrumconsults.io">
              info@spectrumconsults.io
            </a>
            , and phone number +442070434509 is committed to protecting your
            privacy. This Privacy Policy explains how Spectrum Consults
            collects, uses, and discloses your personal information.
          </p>
          <p>
            This Privacy Policy applies to our website and its associated
            subdomains (collectively, our &ldquo;Service&rdquo;) alongside our
            application, Spectrum Consults. By accessing or using our Service,
            you signify that you have read, understood, and agree to our
            collection, storage, use, and disclosure of your personal
            information as described in this Privacy Policy and our Terms and
            Conditions.
          </p>
          <h2>Terms and Definitions</h2>
          <ul>
            <li>
              <strong>Cookie:</strong> A small amount of data generated by a
              website and saved by your web browser. It is used to identify your
              browser, provide analytics, and remember information about you,
              such as your language preference or login information.
            </li>
            <li>
              <strong>Company:</strong> When this policy mentions
              &ldquo;Company,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
              &ldquo;our,&rdquo; it refers to SPECTRUM GROWTH LIMITED (128 City
              Road, London, United Kingdom, EC1V 2NX), which is responsible for
              your information under this Privacy Policy.
            </li>
            <li>
              <strong>Country:</strong> Where Spectrum Consults or the
              owners/founders of Spectrum Consults are based, in this case, is
              the United Kingdom.
            </li>
            <li>
              <strong>Customer:</strong> This refers to the company,
              organisation, or person that signs up to use the Spectrum Consults
              Service to manage relationships with your consumers or service
              users.
            </li>
            <li>
              <strong>Device:</strong> Any internet-connected device, such as a
              phone, tablet, computer, or other device, can be used to visit
              Spectrum Consults and use the services.
            </li>
            <li>
              <strong>IP address</strong>: Every device connected to the
              Internet is assigned a number known as an Internet protocol (IP)
              address. These numbers are usually assigned in geographic blocks.
              An IP address can often identify the location from which a device
              connects to the Internet.
            </li>
            <li>
              <strong>Personnel:</strong> Refers to those individuals employed
              by Spectrum Consults or are under contract to perform a service on
              behalf of one of the parties.
            </li>
            <li>
              <strong>Personal Data:</strong> Any information that, directly,
              indirectly, or in connection with other information &mdash;
              including a personal identification number &mdash; allows for the
              identification or identifiability of a natural person.
            </li>
            <li>
              <strong>Service:</strong> Refers to the Service provided by
              Spectrum Consults as described in the relative terms (if
              available) and on this platform.
            </li>
            <li>
              <strong>Third-Party Service: </strong>Relates to advertisers,
              contest sponsors, promotional and marketing partners, and others
              who provide our content or whose products or services we think may
              interest you.
            </li>
            <li>
              <strong>Website:</strong> SPECTRUM GROWTH LIMITED&rsquo;s site can
              be accessed via this URL:{" "}
              <a href="https://spectrumconsults.io/">
                https://spectrumconsults.io/
              </a>
              .
            </li>
            <li>
              <strong>You:</strong> A person or entity registered with Spectrum
              Consults to use the Services.
            </li>
          </ul>
          <h2>Information We Collect</h2>
          <p>
            We collect information when you visit our website, register, place
            an order, subscribe to our newsletter, respond to a survey, or fill
            out a form.
          </p>
          <ul>
            <li>Name / Username</li>
            <li>Phone Numbers</li>
            <li>Email Addresses</li>
            <li>Mailing Addresses</li>
            <li>Billing Addresses</li>
            <li>Age</li>
            <li>Password</li>
          </ul>
          <h2>
            When Does Spectrum Consults Use Information from Third Parties?
          </h2>
          <p>
            When you contact us, we receive some information from third parties.
            For example, when you submit your email address to show interest in
            becoming a Spectrum Consults customer, we receive information from a
            third party that provides automated fraud detection services to
            Spectrum Consults. We also occasionally collect information that is
            made publicly available on social media websites. You can control
            how much of your information social media websites make public by
            visiting these websites and changing your privacy settings.
          </p>
          <h2>External Website Links</h2>
          <p>
            This Privacy Policy applies only to the Services. The Services may
            contain links to websites not operated or controlled by Spectrum
            Consults. We are not responsible for the content, accuracy, or
            opinions expressed on such websites, and such websites are not
            investigated, monitored, or checked for accuracy or completeness by
            us. Please remember that our Privacy Policy is no longer in effect
            when you use a link from the Services to another website. Your
            browsing and interaction on any other website, including those with
            a link on our platform, is subject to that website&rsquo;s rules and
            policies. Third parties may use cookies or other methods to collect
            information about you.
          </p>
          <h2>How Do We Safeguard Your Information?</h2>
          <p>
            We implement a variety of security measures to maintain the safety
            of your personal information when you place an order or enter,
            submit, or access your personal information. We offer the use of a
            secure server. All supplied sensitive/credit information is
            transmitted via Secure Socket Layer (SSL) technology and then
            encrypted into our Payment gateway providers&rsquo; database only to
            be accessible by those authorised with special access rights to such
            systems and are required to keep the information confidential. After
            a transaction, your private information (credit cards, social
            security numbers, financials, etc.) is never kept on file. We
            cannot, however, ensure or warrant the absolute security of any
            information you transmit to Spectrum Consults or guarantee that your
            information on the Service may not be accessed, disclosed, altered,
            or destroyed by a breach of any of our physical, technical, or
            managerial safeguards.
          </p>
          <h2>How Can I Update or Correct My Information?</h2>
          <p>
            Your rights to request updates or corrections to the information
            Spectrum Consults collects depend on your relationship with Spectrum
            Consults. Personnel may update or correct their information as
            detailed in our internal company employment policies.
          </p>
          <p>
            Customers have the right to request the restriction of specific uses
            and disclosures of personally identifiable information. You can
            contact us at:
          </p>
          <ol>
            <li>Update or correct your personally identifiable information.</li>
            <li>
              Change your preferences concerning communications and other
              information you receive from us.
            </li>
            <li>
              Cancelling your account will delete the personally identifiable
              information maintained about you on our systems (subject to the
              following paragraph).
            </li>
          </ol>
          <p>
            Such updates, corrections, changes, and deletions will not affect
            other information we maintain or have provided to third parties
            following this Privacy Policy before such updates, corrections,
            changes, or deletions. To protect your privacy and security, we may
            take reasonable steps (such as requesting a unique password) to
            verify your identity before granting you profile access or making
            corrections. You are responsible for maintaining the secrecy of your
            unique password and account information.
          </p>
          <p>
            You should be aware that it is not technologically possible to
            remove every record of the information you have provided us from our
            system. The need to back up our systems to protect information from
            accidental loss means that a copy of your data may exist in a
            non-erasable form that will be difficult or impossible for us to
            locate. Promptly after receiving your request, all personal
            information stored in databases we actively use, as well as other
            readily searchable media, will be updated, corrected, changed, or
            deleted, as appropriate, as soon as possible, and reasonably and
            technically practicable.
          </p>
          <h2>Third-Party Providers</h2>
          <p>
            We may display, include, or make available third-party content
            (including data, information, applications, and other products and
            services) or provide links to third-party websites or services
            (&ldquo;Third-Party Services&rdquo;).
          </p>
          <p>
            You acknowledge and agree that Spectrum Consults shall not be
            responsible for any Third-Party Services, including their accuracy,
            completeness, timeliness, validity, copyright compliance, legality,
            decency, quality, or any other aspect thereof. Spectrum Consults
            does not assume and shall not have any liability or responsibility
            to you or any other person or entity for any Third-Party Services.
          </p>
          <p>
            Third-party services and links to them are provided solely for your
            convenience. You access and use them entirely at your own risk and
            subject to such third parties&rsquo; terms and conditions.
          </p>
          <h2>Applicable Law</h2>
          <p>
            The laws of the United Kingdom govern this Privacy Policy without
            regard to its conflict of laws provision. You consent to the
            exclusive jurisdiction of the courts in connection with any action
            or dispute arising between the parties under or in connection with
            this Privacy Policy.
          </p>
          <p>
            The laws of the United Kingdom, excluding its conflicts of law
            rules, shall govern this Agreement and your use of the website. Your
            website use may also be subject to local, state, national, or
            international laws.
          </p>
          <p>
            Using Spectrum Consults or contacting us directly signifies your
            acceptance of this Privacy Policy. If you disagree with this Policy,
            you should not use our website or services. Continued use of the
            website, direct engagement with us, or following the posting of
            changes to this Privacy Policy that do not significantly affect the
            use or disclosure of your personal information will mean that you
            accept those changes.
          </p>
          <h2>Your Agreement</h2>
          <p>
            We&rsquo;ve updated our Privacy Policy to provide complete
            transparency into what is set when you visit our site and its use.
            By using our website, registering an account, or purchasing, you
            consent to our Privacy Policy and agree to its terms.
          </p>
          <h2>Children&rsquo;s Privacy</h2>
          <p>
            We do not address anyone under the age of 18 and do not knowingly
            collect personally identifiable information from anyone under 18. If
            you are a parent or guardian and know that your child has provided
            us with Personal Data, please contact us. Suppose we become aware
            that we have collected Personal Data from anyone under the age of 18
            without verification of parental consent. In that case, we will
            remove that information from our servers.
          </p>
          <h2>Details on General Data Protection Regulation (GDPR)</h2>
          <p>
            We may collect and use your information if you are from the European
            Economic Area (EEA). In this section of our Privacy Policy, we will
            explain exactly how and why this data is collected and how we
            protect it from being replicated or used incorrectly.
          </p>
          <h2>Understanding GDPR</h2>
          <p>
            GDPR is an EU-wide privacy and data protection law regulating how
            companies protect EU residents&rsquo; data and enhance their control
            over it.
          </p>
          <p>
            The GDPR is relevant to any globally operating company, not just
            EU-based businesses and EU residents. Our customers&rsquo; data is
            essential irrespective of location, so we have implemented GDPR
            controls as our baseline standard for all our operations worldwide.
          </p>
          <h2>
            Your Rights Under GDPR &ndash; Access, Portability, and Deletion of
            Data
          </h2>
          <p>
            We are committed to helping our customers meet the GDPR&rsquo;s data
            subject rights requirements. Spectrum Consults processes or stores
            all personal data in fully vetted, DPA-compliant vendors. We store
            all conversations and personal data for up to 6 years unless your
            account is deleted. In this case, we dispose of all data in
            accordance with our Terms of Service and Privacy Policy, but we will
            not hold it for longer than 60 days.
          </p>
          <p>
            We know that if you are working with EU customers, you need to be
            able to provide them with the ability to access, update, retrieve,
            and remove personal data. We got you! We&rsquo;ve been set up as a
            self-service and have always given you access to your and your
            customers&rsquo; data. Our customer support team is here for you to
            answer any questions you might have about working with the API.
          </p>
          <h2>Contact Information</h2>
          <p>
            If you have any questions about this Privacy Policy, please get in
            touch with Spectrum Consults:
          </p>
          <ul>
            <li>
              Via email at{" "}
              <a href="mailto:info@spectrumconsults.io">
                info@spectrumconsults.io
              </a>
              ;
            </li>
            <li>By phone at +442070434509;</li>
            <li>
              Or through the contact form provided on the website:{" "}
              <a href="https://spectrumconsults.io/get-in-touch">
                https://spectrumconsults.io/get-in-touch
              </a>
              .
            </li>
          </ul>
        </div>
      </div>
    </section>
  );
};

export default PolicyPage;
